[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Anshil P", email = "contactme@anshil.me"},
]
license = {text = "MIT"}
dependencies = []
requires-python = ">=3.11"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
